import oracledb
import json
import random

# ================= Configuration =================
def get_db_connection():
    # ⚠️ Replace with your real username and password
    conn = oracledb.connect("s2677882/weiheng0502@@geoslearn", config_dir="/etc/")
    return conn

def setup_database_v2():
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        print("1. Database connection successful! Resetting data...")

        # ================= A. Drop Old Tables (If Exist) =================
        tables = ["MOCK_GREENSPACES", "MOCK_NEIGHBOURHOODS"]
        for table in tables:
            try:
                cursor.execute(f"DROP TABLE {table} PURGE")
                print(f"   🗑️ Dropped old table: {table}")
            except oracledb.DatabaseError:
                print(f"   (Table {table} did not exist, skipping drop)")

        # ================= B. Create Enhanced Neighbourhood Table =================
        # New columns: pop_density, stress_index (simulating GWR results)
        sql_create_nb = """
            CREATE TABLE MOCK_NEIGHBOURHOODS (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR2(100),
                health_index NUMBER,      -- Mental Health Index (0-100)
                simd_rank NUMBER,         -- SIMD Rank (1-10, 1=Most Deprived)
                stress_index NUMBER,      -- Stress Index (Simulated GWR local coefficient)
                population NUMBER,
                geojson_text CLOB,
                center_lat NUMBER,        -- For positioning map center
                center_lon NUMBER,
                PRIMARY KEY (id)
            )
        """
        cursor.execute(sql_create_nb)
        print("2. New Neighbourhoods table created successfully!")

        # Mock Data: Typical areas in Edinburgh
        # Using simple rectangles for clickability
        nb_data = [
            # Name, Health, SIMD, Stress, Pop, Lat, Lon, Geometry
            ("City Centre", 75, 5, 0.4, 15000, 55.950, -3.190, 
             json.dumps({"type":"Polygon", "coordinates":[[[-3.20, 55.945], [-3.18, 55.945], [-3.18, 55.955], [-3.20, 55.955], [-3.20, 55.945]]] })),
            
            ("Leith (High Density)", 62, 3, 0.8, 25000, 55.970, -3.170,
             json.dumps({"type":"Polygon", "coordinates":[[[-3.18, 55.965], [-3.16, 55.965], [-3.16, 55.975], [-3.18, 55.975], [-3.18, 55.965]]] })),
            
            ("Morningside (Affluent)", 88, 10, 0.2, 12000, 55.925, -3.210,
             json.dumps({"type":"Polygon", "coordinates":[[[-3.22, 55.920], [-3.20, 55.920], [-3.20, 55.930], [-3.22, 55.930], [-3.22, 55.920]]] })),
            
            ("Gorgie (Deprived)", 55, 2, 0.9, 18000, 55.935, -3.230,
             json.dumps({"type":"Polygon", "coordinates":[[[-3.24, 55.930], [-3.22, 55.930], [-3.22, 55.940], [-3.24, 55.940], [-3.24, 55.930]]] })),
             
            ("Holyrood (Mixed)", 70, 6, 0.5, 8000, 55.950, -3.160,
             json.dumps({"type":"Polygon", "coordinates":[[[-3.17, 55.945], [-3.15, 55.945], [-3.15, 55.955], [-3.17, 55.955], [-3.17, 55.945]]] }))
        ]

        for row in nb_data:
            cursor.execute(
                "INSERT INTO MOCK_NEIGHBOURHOODS (name, health_index, simd_rank, stress_index, population, center_lat, center_lon, geojson_text) VALUES (:1, :2, :3, :4, :5, :6, :7, :8)",
                row
            )
        print(f"   Inserted {len(nb_data)} detailed neighbourhood records.")

        # ================= C. Create Enhanced Greenspace Table =================
        # New columns: facilities, accessibility_score
        sql_create_gs = """
            CREATE TABLE MOCK_GREENSPACES (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR2(100),
                type VARCHAR2(50),
                quality_score NUMBER,     -- PQA (0-100)
                facilities VARCHAR2(200), -- Desc: e.g. 'Playground, Cafe'
                lat NUMBER,
                lon NUMBER,
                PRIMARY KEY (id)
            )
        """
        cursor.execute(sql_create_gs)
        print("3. New Greenspaces table created successfully!")

        greenspaces = [
            ("The Meadows", "Public Park", 85, "Cafe, Tennis, Playground", 55.9413, -3.1906),
            ("Princes St Gardens", "Public Park", 92, "Monuments, Toilets, Cafe", 55.9507, -3.2003),
            ("Holyrood Park", "Semi-natural", 95, "Hiking, Parking, Viewpoint", 55.9441, -3.1618),
            ("Leith Links", "Public Park", 65, "Playground, Cricket", 55.9723, -3.1607),
            ("Saughton Park", "Public Park", 82, "Skatepark, Rose Garden, Cafe", 55.9360, -3.2380),
            ("Harrison Park", "Public Park", 78, "Canal access, Playground", 55.9370, -3.2190),
            ("Blackford Hill", "Semi-natural", 88, "Viewpoint, Observatory", 55.9244, -3.1950)
        ]

        cursor.executemany(
            "INSERT INTO MOCK_GREENSPACES (name, type, quality_score, facilities, lat, lon) VALUES (:1, :2, :3, :4, :5, :6)",
            greenspaces
        )
        print(f"   Inserted {len(greenspaces)} greenspace records.")

        conn.commit()
        cursor.close()
        conn.close()
        print("\n✅ Database upgrade complete! Old data cleared, new data ready.")

    except Exception as e:
        print(f"\n❌ Error occurred: {e}")

if __name__ == "__main__":
    setup_database_v2()