import oracledb
import json

# ================= 配置 =================
def get_db_connection():
    # ⚠️ 替换为你的真实账号密码
    conn = oracledb.connect("s2677882/weiheng0502@@geoslearn", config_dir="/etc/")
    return conn

def setup_database():
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        print("1. 数据库连接成功！")

        # ================= 清理旧表 (如果存在) =================
        tables = ["MOCK_GREENSPACES", "MOCK_NEIGHBOURHOODS"]
        for table in tables:
            try:
                cursor.execute(f"DROP TABLE {table}")
                print(f"   已删除旧表: {table}")
            except oracledb.DatabaseError:
                pass # 表不存在也没关系

        # ================= 2. 创建绿地表 (Points) =================
        # 我们用简单的 NUMBER 存经纬度，不用复杂的 SDO_GEOMETRY，方便初学者
        sql_create_gs = """
            CREATE TABLE MOCK_GREENSPACES (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR2(100),
                type VARCHAR2(50),
                quality_score NUMBER,
                lat NUMBER,
                lon NUMBER,
                PRIMARY KEY (id)
            )
        """
        cursor.execute(sql_create_gs)
        print("2. 绿地表创建成功！")

        # 插入爱丁堡著名绿地数据 (模拟的 PQA 分数)
        greenspaces = [
            ("The Meadows", "Public Park", 85, 55.9413, -3.1906),
            ("Princes Street Gardens", "Public Park", 92, 55.9507, -3.2003),
            ("Holyrood Park", "Semi-natural", 95, 55.9441, -3.1618),
            ("Inverleith Park", "Public Park", 78, 55.9642, -3.2148),
            ("Leith Links", "Public Park", 65, 55.9723, -3.1607),
            ("Calton Hill", "Historic", 88, 55.9549, -3.1827),
            ("Blackford Hill", "Semi-natural", 82, 55.9244, -3.1950)
        ]

        cursor.executemany(
            "INSERT INTO MOCK_GREENSPACES (name, type, quality_score, lat, lon) VALUES (:1, :2, :3, :4, :5)",
            greenspaces
        )
        print(f"   已插入 {len(greenspaces)} 条绿地数据。")

        # ================= 3. 创建社区表 (Polygons) =================
        # 为了简单，我们把多边形坐标直接存成长字符串 (CLOB)，前端拿到直接用
        sql_create_nb = """
            CREATE TABLE MOCK_NEIGHBOURHOODS (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR2(100),
                health_index NUMBER, 
                simd_rank NUMBER,
                geojson_text CLOB,
                PRIMARY KEY (id)
            )
        """
        cursor.execute(sql_create_nb)
        print("3. 社区表创建成功！")

        # 模拟两个简单的社区多边形 (GeoJSON 格式的 Geometry 部分)
        # 1. 市中心区域 (City Centre)
        poly_central = json.dumps({
            "type": "Polygon",
            "coordinates": [[
                [-3.21, 55.95], [-3.18, 55.96], [-3.15, 55.95], [-3.18, 55.94], [-3.21, 55.95]
            ]]
        })
        
        # 2. 南部区域 (Southside)
        poly_south = json.dumps({
            "type": "Polygon",
            "coordinates": [[
                [-3.20, 55.93], [-3.16, 55.93], [-3.16, 55.94], [-3.20, 55.94], [-3.20, 55.93]
            ]]
        })

        neighbourhoods = [
            ("City Centre", 72, 5, poly_central),
            ("Southside", 68, 3, poly_south)
        ]

        cursor.executemany(
            "INSERT INTO MOCK_NEIGHBOURHOODS (name, health_index, simd_rank, geojson_text) VALUES (:1, :2, :3, :4)",
            neighbourhoods
        )
        print(f"   已插入 {len(neighbourhoods)} 条社区数据。")

        conn.commit()
        cursor.close()
        conn.close()
        print("\n✅ 所有模拟数据准备就绪！")

    except Exception as e:
        print(f"\n❌ 发生错误: {e}")

if __name__ == "__main__":
    setup_database()